name: cellsnap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.3.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cffi=1.15.0
  - colorama=0.4.5
  - cryptography=39.0.1
  - curl=7.83.1
  - cycler=0.11.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - double-conversion=3.2.0
  - eigen=3.3.7
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.4.1
  - flit-core=3.7.1
  - freetype=2.11.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=70.1
  - importlib_resources=5.7.1
  - ipykernel=6.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsoncpp=1.9.5
  - jupyter_client=7.3.1
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.0.0
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.8
  - libdrm=2.4.114
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=12.1.0
  - libhwloc=2.8.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.20
  - libpciaccess=0.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtasn1=4.16.0
  - libtheora=1.1.1
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.17.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - libzip=1.8.0
  - libzlib=1.2.11
  - loguru=0.5.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - nbclient=0.6.4
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - notebook=6.4.11
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.0.8
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.1
  - pooch=1.4.0
  - proj=9.0.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pystackreg=0.2.6
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.9
  - pyvista=0.38.1
  - readline=8.1
  - scooby=0.7.1
  - send2trash=1.8.0
  - setuptools=62.3.1
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - svt-av1=1.1.0
  - tbb=2021.7.0
  - tbb-devel=2021.7.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - tzdata=2022a
  - utfcpp=3.2.1
  - vtk=9.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxt=1.2.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - alabaster==0.7.12
    - async-timeout==4.0.2
    - babel==2.10.1
    - bokeh==2.4.3
    - cachey==0.2.1
    - cellpose==0.6.5
    - cellpose-napari==0.1.4
    - certifi==2022.5.18
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cloudpickle==2.0.0
    - cmocean==2.0
    - colorcet==3.0.1
    - contourpy==1.0.7
    - csbdeep==0.7.2
    - dask==2022.5.0
    - deprecated==1.2.13
    - docstring-parser==0.14.1
    - docutils==0.17.1
    - fastremap==1.12.2
    - fonttools==4.33.3
    - freetype-py==2.3.0
    - frozenlist==1.3.3
    - fsspec==2022.3.0
    - h5py==3.8.0
    - heapdict==1.0.1
    - hsluv==5.0.2
    - humanize==4.1.0
    - idna==3.3
    - imagecodecs==2022.2.22
    - imageio==2.19.2
    - imagesize==1.3.0
    - importlib-metadata==4.11.3
    - ipycanvas==0.13.1
    - ipydatawidgets==4.3.3
    - ipyevents==2.0.1
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - ipyvtklink==0.2.3
    - jsonschema==4.5.1
    - kiwisolver==1.4.2
    - llvmlite==0.38.0
    - locket==1.0.0
    - magicgui==0.4.0
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - meshio==5.3.4
    - monai==0.8.1
    - multidict==6.0.4
    - napari==0.4.15
    - napari-console==0.0.4
    - napari-plugin-engine==0.2.0
    - napari-svg==0.1.6
    - natsort==8.1.0
    - networkx==2.8.1
    - nibabel==3.2.2
    - npe2==0.3.0
    - numba==0.55.1
    - numpy==1.21.6
    - numpydoc==1.3.1
    - opencv-python-headless==4.5.5.64
    - pandas==1.4.2
    - panel==0.14.4
    - param==1.13.0
    - partd==1.2.0
    - pillow==9.1.1
    - pint==0.19.2
    - plotly==5.8.0
    - psutil==5.9.0
    - psygnal==0.3.4
    - pyct==0.5.0
    - pydantic==1.9.1
    - pygments==2.14.0
    - pyopengl==3.1.6
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.10.1
    - pythreejs==2.4.2
    - pytomlpp==1.0.11
    - pytz==2022.1
    - pyviz-comms==2.2.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.0.0
    - qtconsole==5.3.0
    - qtpy==2.1.0
    - requests==2.27.1
    - rich==13.3.2
    - scikit-image==0.19.2
    - scipy==1.8.1
    - seaborn==0.12.2
    - simpleitk==2.1.1.2
    - snowballstemmer==2.2.0
    - sphinx==4.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stardist==0.8.3
    - superqt==0.3.2
    - tenacity==8.0.1
    - tifffile==2022.5.4
    - toolz==0.11.2
    - torch==1.11.0
    - torchio==0.18.77
    - torchvision==0.12.0
    - traitlets==5.2.1.post0
    - traittypes==0.2.1
    - trame==2.3.2
    - trame-client==2.7.4
    - trame-components==2.1.0
    - trame-deckgl==2.0.1
    - trame-markdown==2.0.2
    - trame-matplotlib==2.0.1
    - trame-plotly==2.1.0
    - trame-rca==0.3.0
    - trame-router==2.0.1
    - trame-server==2.9.1
    - trame-simput==2.3.1
    - trame-vega==2.0.2
    - trame-vtk==2.3.4
    - trame-vuetify==2.2.4
    - typer==0.4.1
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - vispy==0.10.0
    - wrapt==1.14.1
    - wslink==1.10.1
    - yarl==1.8.2
